{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- range $key, $val := $.Values.configmap }}
  {{ $key | quote }}: {{ $val | quote }}
{{- end }}
{{- end }}

