apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pubsub-service-account
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  key.json: {{ .Values.secret.PUBSUB_ACCOUNT }}
