apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
spec:
  template:
    spec:
      containers:
        - name: ${PROJECT_NAME}
          volumeMounts:
            - mountPath: "/var/secrets/google"
              name: google-credentials
              readOnly: true
      volumes:
        - name: google-credentials
          secret:
            secretName: ${PROJECT_NAME}-sa