apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${PROJECT_NAME}
spec:
  maxReplicas: 10 
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${PROJECT_NAME}
  targetCPUUtilizationPercentage: 70