apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
spec:
  template:
    spec:
      containers:
        - name: ${PROJECT_NAME}
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 600m
              memory: 512Mi